# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cortex < Formula
  desc "Persistent memory for AI coding agents — knowledge graph, importance scoring, vector search"
  homepage "https://github.com/lleontor705/cortex"
  version "2.3.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lleontor705/cortex/releases/download/v2.3.9/cortex_2.3.9_darwin_amd64.tar.gz"
      sha256 "113e7ba42271c5727795878ee14aa6b8871b09ab08ea484a8fda0a9f0c331a75"

      define_method(:install) do
        bin.install "cortex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lleontor705/cortex/releases/download/v2.3.9/cortex_2.3.9_darwin_arm64.tar.gz"
      sha256 "d0464ad0c86d409756d7e50187c4f69b741d9d94b18e8a82445616e1d6fc313a"

      define_method(:install) do
        bin.install "cortex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lleontor705/cortex/releases/download/v2.3.9/cortex_2.3.9_linux_amd64.tar.gz"
      sha256 "e0e351b5a01727dea61737b9f37043ed2a3da70319042eab83af9e6d2a1b398d"
      define_method(:install) do
        bin.install "cortex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lleontor705/cortex/releases/download/v2.3.9/cortex_2.3.9_linux_arm64.tar.gz"
      sha256 "f5876e2192514a55d10b570f309c7dea01a3360e96d7bcee173e32a131cbdec5"
      define_method(:install) do
        bin.install "cortex"
      end
    end
  end
end
