# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cortex < Formula
  desc "Persistent memory for AI coding agents — knowledge graph, importance scoring, vector search"
  homepage "https://github.com/lleontor705/cortex"
  version "2.4.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lleontor705/cortex/releases/download/v2.4.11/cortex_2.4.11_darwin_amd64.tar.gz"
      sha256 "c09928a3b822543fe003438a9045f2bc415ed84d19276d3d765c135b04133e70"

      define_method(:install) do
        bin.install "cortex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lleontor705/cortex/releases/download/v2.4.11/cortex_2.4.11_darwin_arm64.tar.gz"
      sha256 "2436f695055e7385ddecd2b6a25fb443006fb3020e5214d278058e70d0a822a6"

      define_method(:install) do
        bin.install "cortex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lleontor705/cortex/releases/download/v2.4.11/cortex_2.4.11_linux_amd64.tar.gz"
      sha256 "4d52d2fba3d2619ccf4352670fdc973645e06ab083d94267bde5b8c8cdacf1d9"
      define_method(:install) do
        bin.install "cortex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lleontor705/cortex/releases/download/v2.4.11/cortex_2.4.11_linux_arm64.tar.gz"
      sha256 "a1b6e207f58d046cbbfb4b2c2f9ee18b7b74883cb744e089726455904d92448c"
      define_method(:install) do
        bin.install "cortex"
      end
    end
  end
end
